name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: List files in the repository
        run: ls -R
        
      - name: Zip module
        run: (cd module && zip -r ../oneplus13t-fix-signal-${{ env.VERSION }}.zip .)

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: oneplus13t-fix-signal-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}